# -*- coding: utf-8 -*-
"""Data_Pre-Processing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DVgsUTYUKD8LJbGTRX1jNOm3iqcOEjiD
"""

# ==========================================
# LOCAL PREPROCESSING PIPELINE
# APIGen (80k) + UltraChat (15k) → Mixed SFT Dataset
# No GPU needed — CPU-only preprocessing
# ==========================================
# !pip install datasets transformers -q

# Local execution, no drive mount needed

import json
import random
from datasets import load_dataset, concatenate_datasets, DatasetDict

# ==========================================
# 1. CONFIG — edit only this block
# ==========================================
APIGEN_LIMIT      = 60_000
ULTRACHAT_LIMIT   = 40_000
VAL_RATIO         = 0.02      # 2% → ~2k val samples
SEED              = 42
SAVE_DIR          = r"C:\Users\raiha\OneDrive\Desktop\Msc_proj\ToolForge LLM\dataset"

# ==========================================
# 2. SYSTEM PROMPTS & INSTRUCTION POOL
# ==========================================

TASK_INSTRUCTIONS = [
    "You are a helpful AI assistant with access to tools.",
    "Use available tools when required to answer the user.",
    "Call functions when necessary, otherwise respond naturally.",
]

FORMAT_INSTRUCTION_BLOCK = """[BEGIN OF FORMAT INSTRUCTION]
Output MUST be a JSON object with a "tool_calls" key. No other text.
If no call is needed, set tool_calls to an empty list.
Example:
{{"tool_calls": [{{"name": "func_name", "arguments": {{"arg1": "val1"}}}}]}}
[END OF FORMAT INSTRUCTION]"""

# Single shared template for BOTH APIGen and UltraChat.
# APIGen   → {formatted_tools} = real tool schemas (JSON string)
# UltraChat → {formatted_tools} = "[]"  (empty array → negative sample)
#
# Using ONE template ensures both sources produce structurally identical
# prompts. The model can only distinguish them via the tools content —
# which is exactly the signal we want it to learn to use.
SYSTEM_PROMPT_TEMPLATE = """\
[BEGIN OF TASK INSTRUCTION]
{task_instruction}
[END OF TASK INSTRUCTION]

[BEGIN OF AVAILABLE TOOLS]
{formatted_tools}
[END OF AVAILABLE TOOLS]

""" + FORMAT_INSTRUCTION_BLOCK


# ==========================================
# 3. FORMATTING & CHECKING FUNCTIONS
# ==========================================

def process_apigen(example, shuffle_tools=True):
    """
    Convert one xLAM/APIGen row → unified conversation format.

    xLAM schema per row:
      - tools:   JSON string → list of {name, description, parameters}
                 where parameters IS already a full JSON schema object:
                 {"type": "object", "properties": {...}, "required": [...]}
      - answers: JSON string → list of {name, arguments}
      - query:   string

    Critical: tool["parameters"] is passed through directly — do NOT
    re-wrap it in another {"type":"object","properties":...} layer.
    That produces malformed tool schemas that silently corrupt training.
    """
    try:
        raw_tools   = json.loads(example["tools"])
        raw_answers = json.loads(example["answers"])
    except (json.JSONDecodeError, TypeError, KeyError):
        return {"conversation": [], "source": "apigen"}

    if not raw_tools or not raw_answers:
        return {"conversation": [], "source": "apigen"}

    # Tool order shuffling — prevents positional bias
    # (model learning "call whichever tool appears first")
    if shuffle_tools:
        raw_tools = raw_tools.copy()
        random.shuffle(raw_tools)

    formatted_tools = []
    for tool in raw_tools:
        if not isinstance(tool, dict) or "name" not in tool:
            return {"conversation": [], "source": "apigen"}

        formatted_tools.append({
            "type": "function",
            "function": {
                "name": tool["name"],
                "description": tool.get("description", ""),
                "parameters": tool.get("parameters", {"type": "object", "properties": {}}),
            }
        })

    # Cross-validate: every answer must reference a tool that actually exists.
    # Drops samples where the label refers to a hallucinated tool name.
    tool_names = {t["function"]["name"] for t in formatted_tools}
    for ans in raw_answers:
        if not isinstance(ans, dict) or "name" not in ans:
            return {"conversation": [], "source": "apigen"}
        if ans["name"] not in tool_names:
            return {"conversation": [], "source": "apigen"}

    formatted_tool_calls = [
        {"name": ans["name"], "arguments": ans.get("arguments", {})}
        for ans in raw_answers
    ]

    task_instruction  = random.choice(TASK_INSTRUCTIONS)
    system_content    = SYSTEM_PROMPT_TEMPLATE.format(
        task_instruction=task_instruction,
        formatted_tools=json.dumps(formatted_tools, indent=2),
    )
    assistant_content = json.dumps({"tool_calls": formatted_tool_calls}, indent=2)

    return {
        "source": "apigen",
        "conversation": [
            {"role": "system",    "content": system_content},
            {"role": "user",      "content": example["query"]},
            {"role": "assistant", "content": assistant_content},
        ]
    }


def process_ultrachat(example):
    """
    Convert one UltraChat row → unified conversation format.

    Negative-sample strategy:
      Identical system prompt structure as APIGen, but formatted_tools="[]".
      Teaches the model: "tool-calling prompt + empty tools list = converse normally."
      Without this, the model associates FORMAT_INSTRUCTION_BLOCK with
      "always output JSON" — regardless of whether tools are present.

    HuggingFaceH4/ultrachat_200k (train_sft split) schema:
      - messages: list of {role, content}
        Roles: "user" | "assistant" (no system turn in raw data)
        Always starts with "user", alternates strictly.
    """
    messages = example.get("messages", [])

    if not messages or len(messages) < 2:
        return {"conversation": [], "source": "ultrachat"}

    if messages[0]["role"] != "user":
        return {"conversation": [], "source": "ultrachat"}

    # Validate strict alternating user/assistant pattern
    for i, msg in enumerate(messages):
        expected = "user" if i % 2 == 0 else "assistant"
        if msg.get("role") != expected:
            return {"conversation": [], "source": "ultrachat"}

    # Quality filters
    for msg in messages:
        content = msg.get("content", "")
        if len(content.strip()) < 20:
            return {"conversation": [], "source": "ultrachat"}
        if "as an ai language model" in content.lower():
            return {"conversation": [], "source": "ultrachat"}

    system_content = (
        "You are a helpful, natural, and friendly AI assistant."
    )

    conversation = [{"role": "system", "content": system_content}]
    for msg in messages:
        conversation.append({
            "role":    msg["role"],
            "content": msg["content"].strip(),
        })

    return {
        "source": "ultrachat",
        "conversation": conversation,
    }


# ==========================================
# 4. LOAD DATASETS
# ==========================================
print("Loading APIGen from HuggingFace...")
try:
    apigen_raw = load_dataset(
        "Salesforce/xlam-function-calling-60k",
        split=f"train[:{APIGEN_LIMIT}]",
        token=""
    )
except Exception as e:
    print(f"Failed to load directly, make sure internet is connected. Error: {e}")
    raise
print(f"  Loaded {len(apigen_raw):,} raw APIGen rows")

print("Loading UltraChat 200k (sampling 40k from train_sft)...")
ultrachat_raw = load_dataset(
    "HuggingFaceH4/ultrachat_200k",
    split=f"train_sft[:{ULTRACHAT_LIMIT}]"
)
print(f"  Loaded {len(ultrachat_raw):,} raw UltraChat rows")


# ==========================================
# 5. PROCESS & FILTER
# ==========================================
print("\nProcessing APIGen...")
apigen_mapped = apigen_raw.map(
    process_apigen,
    remove_columns=apigen_raw.column_names,
    desc="APIGen",
)
apigen_clean = apigen_mapped.filter(lambda x: len(x["conversation"]) > 0)
print(f"  APIGen: {len(apigen_raw):,} → {len(apigen_clean):,} "
      f"({len(apigen_raw) - len(apigen_clean):,} dropped)")

print("\nProcessing UltraChat...")
ultrachat_mapped = ultrachat_raw.map(
    process_ultrachat,
    remove_columns=ultrachat_raw.column_names,
    desc="UltraChat",
)
ultrachat_clean = ultrachat_mapped.filter(lambda x: len(x["conversation"]) > 0)
print(f"  UltraChat: {len(ultrachat_raw):,} → {len(ultrachat_clean):,} "
      f"({len(ultrachat_raw) - len(ultrachat_clean):,} dropped)")


# ==========================================
# 6. MERGE & SHUFFLE
# ==========================================
print("\nMerging and shuffling...")
mixed = concatenate_datasets([apigen_clean, ultrachat_clean])
mixed = mixed.shuffle(seed=SEED)

total      = len(mixed)
tool_count = sum(1 for x in mixed if x["source"] == "apigen")
conv_count = total - tool_count
print(f"\n  Total samples        : {total:,}")
print(f"  Tool-call (APIGen)   : {tool_count:,}  ({tool_count/total:.1%})")
print(f"  Conversational/Neg.  : {conv_count:,}  ({conv_count/total:.1%})")


# ==========================================
# 7. TRAIN / VAL SPLIT
# ==========================================
print(f"\nSplitting: val_ratio={VAL_RATIO}")
split = mixed.train_test_split(test_size=VAL_RATIO, seed=SEED)
dataset_dict = DatasetDict({
    "train": split["train"],
    "val":   split["test"],
})
print(f"  Train : {len(dataset_dict['train']):,}")
print(f"  Val   : {len(dataset_dict['val']):,}")


# ==========================================
# 8. SAVE
# ==========================================
import os
os.makedirs(SAVE_DIR, exist_ok=True)

# HuggingFace DatasetDict format (load_from_disk compatible)
print(f"\nSaving HF dataset to {SAVE_DIR} ...")
dataset_dict.save_to_disk(SAVE_DIR)

# JSONL format — portable, works directly on RunPod without HF datasets config
for split_name in ["train", "val"]:
    out_name = f"new_{split_name}.jsonl"
    out_path = f"{SAVE_DIR}/{out_name}"
    with open(out_path, "w", encoding="utf-8") as f:
        for row in dataset_dict[split_name]:
            f.write(json.dumps(row, ensure_ascii=False) + "\n")
    print(f"  Saved {split_name}.jsonl  ({len(dataset_dict[split_name]):,} rows)")


# ==========================================
# 9. SPOT CHECK — print 1 sample of each type
# ==========================================
print("\n" + "="*65)
print("SPOT CHECK — APIGen sample (tool call)")
print("="*65)
apigen_sample = next(x for x in dataset_dict["train"] if x["source"] == "apigen")
for turn in apigen_sample["conversation"]:
    preview = turn["content"][:400].replace("\n", " ")
    print(f"\n[{turn['role'].upper()}]\n{preview}...")

print("\n" + "="*65)
print("SPOT CHECK — UltraChat sample (negative / conversational)")
print("="*65)
ultrachat_sample = next(x for x in dataset_dict["train"] if x["source"] == "ultrachat")
for turn in ultrachat_sample["conversation"]:
    preview = turn["content"][:300].replace("\n", " ")
    print(f"\n[{turn['role'].upper()}]\n{preview}...")

print("\n✅ Done. Dataset saved to local directory.")
print(f"   HF format  : {SAVE_DIR}/")
print(f"   JSONL train: {SAVE_DIR}/new_train.jsonl")
print(f"   JSONL val  : {SAVE_DIR}/new_val.jsonl")

